refactor vilbert to make it compatible for torchscript
facebookresearch/mmf pull request #591
Opened 2020-09-30 22:56 UTC by neo315

Summary:
Refactor to make vilbert compatible to torchscript
Similar changes are done in [our implementation of Vilbert](https://www.internalfb.com/intern/diffusion/FBS/browsefile/master/fbcode/assistant/mmu/multimodal_bert/vilbert/model.py). ref diff: D18892981

Differential Revision: D23923842

2020-10-06 05:18 UTC, vedanuj requested changes
Thanks for making these changes. Left some comments.

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +#!/usr/bin/env python3
Remove

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +        x = torch.reshape(x, new_x_shape)
```suggestion
        x = x.view(new_x_shape)
```

Using view is better as reshaping might make a copy of the tensor in some cases.

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +        context_layer = torch.reshape(context_layer, new_context_layer_shape)
```suggestion
        context_layer = context_layer.view(new_context_layer_shape)
```

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +        x = torch.reshape(x, new_x_shape)
```suggestion
        x = x.view(new_x_shape)
```

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +        context_layer1 = torch.reshape(context_layer1, new_context_layer_shape1)
Replace `reshape` to `view`

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +        return extended_attention_mask
This is not required with latest pytorch 1.6+. We can guard blocks using 'torch.jit.is_scripting()'. Check the implementation in VisualBERT model.

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +            )
Use `not torch.jit.is_scripting()`

2020-10-06 05:18 UTC, vedanuj commented on mmf/models/vilbert.py
> +        if self.training:
Same

2020-10-14 19:32 UTC, vedanuj approved these changes

2020-10-14 20:37 UTC, apsdehal approved these changes

2020-10-14 21:17 UTC, closed without merging