[fix] use torch current device rather than using registry
facebookresearch/mmf pull request #659
Opened 2020-10-23 19:50 UTC by ytsheng

* Minor fix so that we remove the registry current device dependency, and instead use torch.

2020-10-26 08:03 UTC, vedanuj commented on mmf/datasets/base_dataset.py
> +        )
This can be made into an util function, since I see this being used in multiple places.

2020-10-28 06:12 UTC, apsdehal requested changes
Thanks. This is looking good. Some minor comments and should be good to go after that.

2020-10-28 06:12 UTC, apsdehal commented on mmf/datasets/base_dataset.py
> +from mmf.utils.general import get_device
Probably name it `get_current_device`, `get_device` can refer to any device?

2020-10-28 06:12 UTC, apsdehal commented on mmf/utils/general.py
> +    return (
Since this is a function now, can we write it is as a simple if else condition now?

2020-10-28 06:12 UTC, apsdehal commented on mmf/utils/general.py
> +def get_device():
Even though this is small, it would still be good to write tests for this to catch any pytorch related regressions in future.

2020-10-29 23:39 UTC, apsdehal approved these changes

2020-10-30 00:15 UTC, closed without merging